services:
  - type: web
    name: video-to-gif
    env: python
    pythonVersion: "3.10.0"
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg imagemagick build-essential python3-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 